export const Apps = [
  {
    name: "social",
    title: "Social Media App",
    desc:
      "This advanced social media application has been built with 4 microservices. "+
      "Spring boot restful back-end api for data prosessing, Socket server for instant messaging and notifications and Chat server for storage messenger datas which is using node.js express and mongoDb and lastly React.js client-server.",
    video: "https://player.vimeo.com/video/455097381",
    color: "#5890ff",
    // images: ["social/social1.png", "social/social2.png", "social/social3.png"],
    tech: [
      "Java Spring Boot",
      "React.js",
      "Redux",
      "Redux Saga",
      "Node.js",
      "MySql",
      "MongoDb",
      "Socket.io",
      "Amazon S3",
      "Spring Security",
      "Google Map Api",
      "Html",
      "Css",
      "Bootstrap",
      "Saas",
    ],
  },
  {
    name: "youtube",
    title: "Youtube Clone",
    desc:
      "Functional react components, effective hook functions, clean and responsive design. Enhanced with Google Youtube API.",
    url: "https://clone-a2ef2.web.app",
    github: "https://github.com/safak/React-Youtube-Clone",
    video: "https://player.vimeo.com/video/455097381",
    color: "#ff0000",
    images: [
      "youtube/youtube1.png",
      "youtube/youtube2.png",
      "youtube/youtube3.png",
    ],
    tech: ["React.js", "Youtube API", "Html", "Css"],
  },
  {
    name: "twitter",
    title: "Twitter Clone",
    desc:
      "Firebase firestore database, functional react components, effective hook functions, clean and responsive design.",
    url: "https://twitter-clone-efa1f.web.app",
    github: "https://github.com/safak/React-Twitter-Clone",
    video: "https://player.vimeo.com/video/455100271",
    color: "#50b7f5",
    images: ["twitter/twitter1.png"],
    tech: ["React.js", "Google Firebase", "Html", "Css"],
  },
  {
    name: "google",
    title: "Google Clone",
    desc:
      "Google Search API, functional react components, effective hook functions, clean and responsive design.",
    url: "https://clone-42816.web.app",
    github: "https://github.com/safak/React-Google-Clone",
    video: "https://player.vimeo.com/video/455102974",
    color: "#4285f4",
    images: ["google/google1.png"],
    tech: ["React.js", "Google API", "Html", "Css"],
  },
  {
    name: "hulu",
    title: "Hulu Clone",
    desc:
      "The Movie API, functional react components, effective hook functions, clean and responsive design.",
    url: "https://hulu-clone-24fc3.web.app",
    github: "https://github.com/safak/React-Hulu-Clone",
    video: "https://player.vimeo.com/video/455104210",
    color: "#1ce783",
    images: ["hulu/hulu1.png"],
    tech: ["React.js", "The Movie API", "Html", "Css"],
  },
  {
    name: "netflix",
    title: "Netflix Clone",
    desc:
      "The Movie Database API, functional react components, effective hook functions, clean and responsive design.",
    url: "http://safakkocaoglu.com/react-netflix",
    github: "https://github.com/safak/react-netflix",
    video: "https://player.vimeo.com/video/455108158",
    color: "#e50914",
    images: [
      "netflix/netflix1.png",
      "netflix/netflix2.png",
      "netflix/netflix3.png",
    ],
    tech: ["React.js", "The Movie API", "Html", "Css"],
  },
  {
    name: "shop",
    title: "Online Shop App",
    desc:
      "Google Firebase firestore, functional react components, redux state management, effective hook functions, clean and responsive design.",
    url: "https://react-shop--mess-live.herokuapp.com",
    github: "https://github.com/safak/react-shop",
    video: "https://player.vimeo.com/video/455109399",
    color: "#808282",
    images: ["shop/shop1.png", "shop/shop2.png", "shop/shop3.png"],
    tech: [
      "React.js",
      "Redux",
      "Redux Saga",
      "Firebase",
      "Stripe",
      "Html",
      "Css",
    ],
  },
  {
    name: "slack",
    title: "Slack Clone",
    desc:
      "Google Firebase firestore, functional react components, effective hook functions, clean and responsive design.",
    url: "https://react-slack-clone-app.herokuapp.com",
    github: "https://github.com/safak/React-Slack-Clone",
    video: "https://player.vimeo.com/video/455114916",
    color: "#3f0f40",
    images: ["slack/slack1.png"],
    tech: ["React.js", "Firebase", "Stripe", "Html", "Css"],
  },
];
